version: '3'
services:
  app:
    container_name: crud-node-app
    restart: always
    build: .
    ports:
      - '88:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
